CREATE TABLE Kunde
(
    id SMALLINT NOT NULL AUTO_INCREMENT,
    fornavn VARCHAR(255) NOT NULL,
    etternavn VARCHAR(255) NOT NULL,
    telefonnr VARCHAR(255) NOT NULL,
    epost VARCHAR(255) NOT NULL,
    antall VARCHAR(255) NOT NULL,
    film VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);